// Central registry of DOM nodes for the redesigned app. Modules run as deferred
// ES modules, so the document is already parsed when these queries execute.

const $ = (id) => document.getElementById(id);

export const elements = {
  // shell
  appShell: $("appShell"),
  sessionTimer: $("sessionTimer"),
  authScreen: $("authScreen"),
  appRoot: $("appRoot"),
  dashboardScreen: $("dashboardScreen"),
  boardScreen: $("boardScreen"),

  // rail + dropdowns
  rail: $("rail"),
  railLogo: $("railLogo"),
  railBoards: $("railBoards"),
  railCreate: $("railCreate"),
  dropdownBackdrop: $("dropdownBackdrop"),
  notifButton: $("notifButton"),
  notifBadge: $("notifBadge"),
  notifMenu: $("notifMenu"),
  notifList: $("notifList"),
  clearNotifsButton: $("clearNotifsButton"),
  profileButton: $("profileButton"),
  profileMenu: $("profileMenu"),
  profileMenuAvatar: $("profileMenuAvatar"),
  profileMenuName: $("profileMenuName"),
  profileMenuEmail: $("profileMenuEmail"),
  signOutButton: $("signOutButton"),
  menuProfile: $("menuProfile"),
  menuAccount: $("menuAccount"),
  menuNotif: $("menuNotif"),
  menuHelp: $("menuHelp"),

  // auth
  emailAuthForm: $("emailAuthForm"),
  authName: $("authName"),
  authEmail: $("authEmail"),
  authPassword: $("authPassword"),
  emailSignInButton: $("emailSignInButton"),
  emailSignUpButton: $("emailSignUpButton"),
  googleSignInButton: $("googleSignInButton"),
  authNotice: $("authNotice"),
  authError: $("authError"),

  // dashboard
  enablePushButton: $("enablePushButton"),
  dashWelcome: $("dashWelcome"),
  needsSection: $("needsSection"),
  needsStrip: $("needsStrip"),
  needsCount: $("needsCount"),
  needsActions: $("needsActions"),
  upcomingList: $("upcomingList"),
  dashBoardCount: $("dashBoardCount"),
  newBoardButtonTop: $("newBoardButtonTop"),
  boardCards: $("boardCards"),

  // board header
  boardEmoji: $("boardEmoji"),
  boardName: $("boardName"),
  boardOnline: $("boardOnline"),
  boardSubtitle: $("boardSubtitle"),
  boardNextNight: $("boardNextNight"),
  boardTopGame: $("boardTopGame"),
  boardPendingVotes: $("boardPendingVotes"),
  headerAvatars: $("headerAvatars"),
  boardMemberLabel: $("boardMemberLabel"),
  inviteButton: $("inviteButton"),
  boardSettingsButton: $("boardSettingsButton"),

  // tabs + views
  tabRoster: $("tabRoster"),
  tabSchedule: $("tabSchedule"),
  rosterView: $("rosterView"),
  scheduleView: $("scheduleView"),

  // roster
  rosterSubtitle: $("rosterSubtitle"),
  decisionPanel: $("decisionPanel"),
  spinButton: $("spinButton"),
  proposeGameButton: $("proposeGameButton"),
  wheelResult: $("wheelResult"),
  rotationList: $("rotationList"),
  rotationCount: $("rotationCount"),
  pendingList: $("pendingList"),
  pendingCount: $("pendingCount"),
  rejectedList: $("rejectedList"),
  rejectedCount: $("rejectedCount"),

  // schedule
  availabilityPresets: $("availabilityPresets"),
  proposeTimeButton: $("proposeTimeButton"),
  heatmap: $("heatmap"),
  bestDayLabel: $("bestDayLabel"),
  sessionList: $("sessionList"),

  // chat
  chatPanel: $("chatPanel"),
  chatHeadInfo: $("chatHeadInfo"),
  chatBody: $("chatBody"),
  chatToggle: $("chatToggle"),
  chatOnline: $("chatOnline"),
  chatLog: $("chatLog"),
  chatForm: $("chatForm"),
  chatMessage: $("chatMessage"),
  quickPollButton: $("quickPollButton"),
  shareSessionButton: $("shareSessionButton"),

  // modals
  modalRoot: $("modalRoot"),
  modalProposeGame: $("modalProposeGame"),
  modalInvite: $("modalInvite"),
  modalProposeTime: $("modalProposeTime"),
  modalCreateBoard: $("modalCreateBoard"),

  // propose game
  proposeGameForm: $("proposeGameForm"),
  pgModalTitle: $("pgModalTitle"),
  pgSubmitButton: $("pgSubmitButton"),
  pgTitle: $("pgTitle"),
  pgVariant: $("pgVariant"),
  pgPlayers: $("pgPlayers"),
  pgPlatforms: $("pgPlatforms"),
  pgTags: $("pgTags"),
  pgCatalogLoading: $("pgCatalogLoading"),
  pgCatalogSuggest: $("pgCatalogSuggest"),
  pgCatalogPicked: $("pgCatalogPicked"),

  // invite
  inviteBoardName: $("inviteBoardName"),
  inviteForm: $("inviteForm"),
  inviteEmail: $("inviteEmail"),
  sendInviteButton: $("sendInviteButton"),
  inviteFeedback: $("inviteFeedback"),
  memberList: $("memberList"),
  pendingInvites: $("pendingInvites"),

  // propose time
  proposeTimeForm: $("proposeTimeForm"),
  ptDate: $("ptDate"),
  ptStart: $("ptStart"),
  ptEnd: $("ptEnd"),
  ptLabel: $("ptLabel"),

  // create board
  createBoardForm: $("createBoardForm"),
  cbModalTitle: $("cbModalTitle"),
  cbSubmitButton: $("cbSubmitButton"),
  cbDeleteButton: $("cbDeleteButton"),
  cbEmoji: $("cbEmoji"),
  cbIconPreview: $("cbIconPreview"),
  cbChangePhotoButton: $("cbChangePhotoButton"),
  cbIconFileInput: $("cbIconFileInput"),
  cbIconFeedback: $("cbIconFeedback"),
  cbName: $("cbName"),
  cbMembersSection: $("cbMembersSection"),
  cbMembers: $("cbMembers"),

  // settings modal
  settingsModal: $("settingsModal"),
  settingsPanel: $("settingsPanel"),
  settingsNav: $("settingsNav"),
  settingsTitle: $("settingsTitle"),
  settingsSub: $("settingsSub"),
  settingsBackButton: $("settingsBackButton"),
  paneProfile: $("paneProfile"),
  paneAppearance: $("paneAppearance"),
  paneAccount: $("paneAccount"),
  paneNotif: $("paneNotif"),
  paneHelp: $("paneHelp"),
  settingsAvatar: $("settingsAvatar"),
  settingsName: $("settingsName"),
  settingsEmail: $("settingsEmail"),
  changePhotoButton: $("changePhotoButton"),
  avatarFileInput: $("avatarFileInput"),
  avatarFeedback: $("avatarFeedback"),
  accentPicker: $("accentPicker"),
  profileNameInput: $("profileNameInput"),
  profileStatusInput: $("profileStatusInput"),
  saveProfileButton: $("saveProfileButton"),
  profileFeedback: $("profileFeedback"),
  accountEmail: $("accountEmail"),
  newPass: $("newPass"),
  confirmPass: $("confirmPass"),
  updatePassButton: $("updatePassButton"),
  passFeedback: $("passFeedback"),
  googleStatus: $("googleStatus"),
  googleLinkButton: $("googleLinkButton"),
  notifPrefs: $("notifPrefs"),
  prefPlatforms: $("prefPlatforms"),
  feedbackText: $("feedbackText"),
  sendFeedbackButton: $("sendFeedbackButton"),

  emptyTemplate: $("emptyTemplate")
};
